version: 0.2

phases:
  pre_build:
    commands:
      # 1. Simple direct stable binary download karna (No repo jhanjhat)
      - echo Installing kubectl binary directly...
      - curl -LO "https://k8s.io"
      - chmod +x ./kubectl
      - sudo mv ./kubectl /usr/local/bin/kubectl
      - kubectl version --client
      
      # 2. Docker Hub login
      - echo Logging in to Docker Hub...
      - echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
  
  build:
    commands:
      - echo Build started on `date`
      - docker build -t ahmadansari19/hello-world-app:latest .
  
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push ahmadansari19/hello-world-app:latest
      - echo Connecting to EKS Cluster...
      - aws eks update-kubeconfig --name free-secure-cluster --region us-east-1
      - echo Deploying to EKS...
      - kubectl apply -f deployment.yaml
