version: 0.2

phases:
  install:
    commands:
      - curl -LO "https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/

  pre_build:
    commands:
      - echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin

  build:
    commands:
      - docker build -t ahmadansari19/hello-world-app:latest .

  post_build:
    commands:
      - docker push ahmadansari19/hello-world-app:latest
      - aws eks update-kubeconfig --name free-secure-cluster --region us-east-1
      - kubectl apply -f deployment.yaml --validate=false
